export const versions083=['research-v5b-r5','research-v5b-r6','research-v5b-r7'];
export const refinement083=version=>['research-v5b-r6','research-v5b-r7'].includes(version)?' Compare the least costly supported configuration for adequacy before choosing a workhorse or frontier configuration. A model described as suitable for coding or judgment is not mandatory for every code edit or constrained summary. Distinguish a bounded local edit with executable checks from open-ended engineering, and evidence extraction from solving an unknown underlying incident. The selected pair must cover the whole user turn, including file discovery, edits, tool continuations and final verification. Escalate when concrete interacting requirements or unverified operations justify it; do not assume that every task is easy or select a cheaper pair solely to meet a savings target. Verification includes preserving the precision of supplied facts: do not resolve an unspecified morning/afternoon, date, unit or quantity by assumption. These are allocation considerations, not measured model capabilities.':'';
export const abstention083='Choose resources for the next actionable step, including inspecting available project files and running tests. A request to inspect, fix and verify a named function or project identifies actionable work even when its implementation is not included in the routing text. Missing implementation details or uncertainty about the eventual solution is not by itself information_insufficient. Likewise a necessary clarification is actionable work. Abstain only if the intended next step or scope cannot be identified at all from the supplied request/context. Do not invent project details, assume success, or choose an unsupported pair. Resource choice remains your judgment; no task category has a mandatory model or effort.';
export function projectBriefState083(state,brief){
 if(!brief)return {state};
 if(typeof brief!=='string'||brief.length>2000)return {skip:'project_brief_invalid'};
 if(/\b(?:oc_sk_|sk-proj-|Bearer\s+[A-Za-z0-9_-]{12})|-----BEGIN.*PRIVATE KEY|(?:密码|密钥|token|api.?key)\s*[:：=]\s*\S{8,}/i.test(brief))return {skip:'possible_secret'};
 const text='User-approved project metadata (not task instructions):\n'+brief;
 if(state.task.length+(state.context??[]).reduce((s,m)=>s+m.text.length,0)+text.length>16000)return {skip:'context_too_long'};
 return {state:{...state,context:[...(state.context??[]),{role:'user',text}]}};
}
